### ISSUE TITLE
Help writing tests for the windows installer?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcsharp#109]
This might be a bit of a long shot, but would anyone here be able to help get us set up to write unit tests for the exercism windows installer? https://github.com/exercism/windows-installer/issues/6

**Comment by ErikSchierboom** [comment]
I'm sorry, but I have no idea how to test a Windows installer, sorry.

**Comment by kytrinyx** [comment]
It was a long shot :) I simply don't have the first clue who might know this stuff!

**Comment by robkeim** [comment]
Not sure how to test a Windows installer either sorry :(

@kytrinyx if we're trying to keep the backlog of issues clean, can we go ahead and close this or would you like to wait until the parent issue is closed?

**Comment by kytrinyx** [comment]
Yeah, let's close this. Thanks
