### ISSUE TITLE
Create .NET Core/Visual Studio Code cross-platform setup instructions

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xcsharp#146]
Inspired by #38, esp. comments by @NobbZ and @ErikSchierboom - 

I'm running .NET Core and Visual Studio Code on Ubuntu and it's a dream. Way nicer for doing exercism exercises than the ceremony and overkill of Visual Studio, and it's easily installed on Windows, OS X, and Linux... https://www.microsoft.com/net/core#linuxubuntu has dead simple instructions and ends with a link to download VS Code... 

I think it might be well worth doing a cross-platform howto with a unified workflow, then have Visual Studio / Xamarin as an advanced/alternative option; VS and MonoDevelop are fine for people who are already using them, but with the amount of **HALP!** requests getting started w/ C# and/or F# on Gitter, streamlining the process with uniform, open-source tools (and _without_ the heavyweight IDEs) seems like a good way to lower the barrier to entry for new users.

**Comment by ErikSchierboom** [comment]
I totally agree! And it is something we are planning on doing, it's just that the .NET Core stuff is still quite a bit in flux. At the moment, Microsoft is working hard to complete the work of reverting he project system to MSBuild (instead of `project.json`). When that is finished, we will be porting all the exercises over to work on .NET Core with all the added benefits.

For some more information, see #138.

**Comment by canweriotnow** [comment]
I'll keep an eye out for when the xcsharp maintainers feel it's mature enough, I'd be happy to help with the porting process. Thanks!

**Comment by ErikSchierboom** [comment]
@canweriotnow Great! We'll post any updates here. By the way, if you're interested in tracking the work Microsoft is doing, you can check the [CLI](https://github.com/dotnet/cli) and [MSBuild](https://github.com/Microsoft/msbuild) repositories.

**Comment by ErikSchierboom** [comment]
As a reminder, we will be updating the docs as part of #200. We should be adding docs for the following scenarios:

- Running from the command-line using the .NET CLI
- Running from Visual Studio
- Running from Visual Code
- Running from Visual Studio for Mac
- Running from Project Rider

It might seem a bit much, but I think this will be worthwhile.

**Comment by ErikSchierboom** [comment]
I've updated the .NET Core PR with some initial docs on how to install or run the tests. If anyone would read and check them, that would be great! Here are the direct links to the files:

- [INSTALLATION.md](https://github.com/ErikSchierboom/xcsharp/blob/1bf058a32c04f0cc35253b406e69271c4b291c28/docs/INSTALLATION.md)
- [TESTS.md](https://github.com/ErikSchierboom/xcsharp/blob/1bf058a32c04f0cc35253b406e69271c4b291c28/docs/TESTS.md)

I've opted to not have detailed instructions on how to run the tests in the various IDE's, as most other language tracks also don't do it. It's also much easier for us maintainers if we have a single, supported way to run the tests. In our case, I opted for the .NET CLI option for three reasons:

1. It's very simple
2. It's similar to how other languages run their tests
3. It's cross-platform (meaning we don't have to duplicate documentation)

CC: @canweriotnow @GalaDe @robkeim @balazsbotond @bressain @jmbradnan

**Comment by robkeim** [comment]
@ErikSchierboom I just had a quick look through the documentation and it looks good! Thanks for all of your work on this.

**Comment by ErikSchierboom** [comment]
@robkeim Thanks! Tomorrow is the Visual Studio 2017 and .NET CLI 1.0 launch. If everything runs fine on those release versions, I'll (finally) merge the .NET Core PR. Would be great to finally have it working. We can then work on further polishing the track. I've actually did some thinking a found lots of ways we can improve things even more. For all of these ideas, I've created a new issue.

**Comment by ErikSchierboom** [comment]
@canweriotnow With #199 merged, I think this issue can now be closed. To be clear, we've updated the track to be based on the .NET CLI, which is cross-platform and thus has the same interface on all platforms. You should thus now have things nicely working on .NET Core!
