### ISSUE TITLE
Verify contents and format of track documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcsharp#147]
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

**Comment by ErikSchierboom** [comment]
I've created a short checklist of things to check:

- [ ] INSTALLATION.md - how to install the language and any dependencies
- [ ] TESTS.md - how to run the tests
- [ ] ABOUT.md - short, enticing introduction to the language
- [ ] LEARNING.md - where to get an introduction to the language if you're learning it for the first time
- [ ] RESOURCES.md - references, tools, etc.
- [ ] Put images in `docs/img`

**Comment by ErikSchierboom** [comment]
@kytrinyx Updating the TESTS.md and INSTALLATION.md is something I'd like to keep open for a while, as we expect to do a rather massive overhoal once F# runs on the updated .NET Core 2.0. That will be sometime in the first quarter of 2017 probably.

**Comment by robkeim** [comment]
@ErikSchierboom I think you mean C# :)

**Comment by ErikSchierboom** [comment]
Ehm, yes. That's what you get when you copy-paste text...
