### ISSUE TITLE
Run build and tests on Mac OS

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#164]
To verify that the code also works on Mac OS, we should modify the Travis build to also run on Mac OS.

**Comment by masters3d** [comment]
The Travis Mac farm is very slow during peak hours for open source projects. Are you running circle CI too?

**Comment by ErikSchierboom** [comment]
@masters3d Yes, we are. And indeed Mac OS builds are slow, but they do run eventually.

**Comment by masters3d** [comment]
Did Katrina turn it on for you? or can we deploy that ourselves. I didn't see circle running on the PR in Github. Whats your set up?

**Comment by robkeim** [comment]
@ErikSchierboom if we only validate Linux do you think there are a lot of bugs that would be on Mac OS only? Most of the changes are for the core C# code and shouldn't be platform specific.

**Comment by ErikSchierboom** [comment]
@masters3d No I turned it on myself, to verify that our code also works on Mac OS
@robkeim I don't expect many Mac OS specific bugs, it's just to be safe
