### ISSUE TITLE
Implement remaining exercises for track

### ISSUE THREAD

**Issue by robkeim** [exercism/xcsharp#171]
@ErikSchierboom mentioned [here](https://github.com/exercism/xcsharp/pull/166#issuecomment-272947351) that we only have four exercises remaining in the C# track to be implemented:

- [x] [error-handling](https://github.com/exercism/x-common/tree/master/exercises/error-handling)
- [x] [forth](https://github.com/exercism/x-common/tree/master/exercises/forth)
- [x] [pov](https://github.com/exercism/x-common/tree/master/exercises/pov)
- [x] [zipper](https://github.com/exercism/x-common/tree/master/exercises/zipper)

There's light at the end of the tunnel :)

**Comment by robkeim** [comment]
@ErikSchierboom - I'll give error-handling a go

**Comment by ErikSchierboom** [comment]
@robkeim Cool!

**Comment by ErikSchierboom** [comment]
@robkeim I'm working on the `pov` exercise.

**Comment by robkeim** [comment]
Sounds good @ErikSchierboom!

**Comment by ErikSchierboom** [comment]
@robkeim I'll probabyl work on the `zipper` exercise tonight.

**Comment by robkeim** [comment]
You're a machine @ErikSchierboom :)

**Comment by ErikSchierboom** [comment]
We'll, I do have the advantage that I already solved it in F#. That means it's more porting than solving :)

**Comment by robkeim** [comment]
Fair enough :)

**Comment by robkeim** [comment]
Thanks @ErikSchierboom, the C# track now has every available exercise implemented 🎉

**Comment by ErikSchierboom** [comment]
Hurray! Thanks for the great help @robkeim!

@kytrinyx We now have all exercises available in C# too! :tada:

**Comment by kytrinyx** [comment]
@robkeim @ErikSchierboom 🎉 Brilliant! 🎈
