### ISSUE TITLE
bank-account: Should GetBalance be a Balance property instead?

### ISSUE THREAD

**Issue by petertseng** [exercism/xcsharp#189]
When I was doing this exercise, I remarked that it seemed unidiomatic that `GetBalance()` was a method, rather than having a `Balance` property.

But y'all know C# better than I do, so y'all are in a better position to answer - must it be a method? Or can/should it be a property?

**Comment by ErikSchierboom** [comment]
It should indeed be a property, good catch!

**Comment by ErikSchierboom** [comment]
@petertseng A [PR](#192) has been opened.

**Comment by robkeim** [comment]
I've just gone ahead and merged the PR. Thanks @petertseng for bringing this up.
