### ISSUE TITLE
pov: Consider making tests insensitive to child ordering 

### ISSUE THREAD

**Issue by petertseng** [exercism/xcsharp#191]
I didn't actually do this exercise in C# so it's possible I misfired, but I think `IsEqual` does what I think it does.

In the [pov tests](https://github.com/exercism/xcsharp/blob/master/exercises/pov/PovTest.cs), given a tree that must be reparented on node x, the tests ensure that the former parent of x comes *after* the former children of x.

Example: The graphs:

```csharp
    private static readonly Graph<string> kids =
        Pov.CreateGraph("root", new[] {
            Pov.CreateGraph(x, new[] {
                Pov.CreateGraph("kid-0", new Graph<string>[0]),
                Pov.CreateGraph("kid-1", new Graph<string>[0])
            })
    });
    private static readonly Graph<string> kids_ = 
        Pov.CreateGraph(x, new[] {
            Pov.CreateGraph("kid-0", new Graph<string>[0]),
            Pov.CreateGraph("kid-1", new Graph<string>[0]),
            Pov.CreateGraph("root", new Graph<string>[0])
    });
```

However, you could imagine that the following ordering is equally valid - it doesn't matter whether the root becomes the last child or the first child!

```csharp
    private static readonly Graph<string> kids_ = 
        Pov.CreateGraph(x, new[] {
            Pov.CreateGraph("root", new Graph<string>[0]),
            Pov.CreateGraph("kid-0", new Graph<string>[0]),
            Pov.CreateGraph("kid-1", new Graph<string>[0])
    });
```

I think it would be beneficial if the tests did not care about the ordering of the children, since trees probably don't care about the ordering of their children, and it almost certainly is valid to allow either order in the POV problem.

Yes, I did copy a lot of this text from https://github.com/exercism/xhaskell/issues/92, sorry. But it is definitely still relevant to this track. If you care to see how I did in Haskell, I test sorted edge list + root, so that child ordering does not matter: https://github.com/exercism/xhaskell/pull/108

**Comment by petertseng** [comment]
I just realized a difficulty with this. `CreateGraph` is **in control of the student**.

So that means, **perhaps it's the student's responsibility** to ensure that `CreateGraph` creates graphs insensitive to child ordering... as well as having the `FromPOV` function ensure that it puts children in the same order as `CreateGraph` would.

In general, this means that because the student is free to use whatever implementation of `CreateGraph`, the graph could have any internal representation, and therefore the tests can't assume anything about it (they can't examine the sorted edges and root at will) unless the test adds more required functions to burden the student more.

**Comment by ErikSchierboom** [comment]
The reason we use `CreateGraph` is indeed to have the student choose his/her own implementation of the tree structure. We used to do exercises where the tree structure was already defined, but people did not really like being forced into using a specific structure.

So either we add more tests, pre-define the tree implementation or leave it as is. I don't really like the first option, but the second option is definitely one we could be using. We could be specifying a default tree implementation, which the user thus would not have to specify itself. What do you think @robkeim and @balazsbotond?

**Comment by petertseng** [comment]
Here is another option that I didn't like when I was thinking about it for Haskell, but I have saved at https://github.com/exercism/xhaskell/pull/107

The idea is, expect that there are two common orderings that students will use: 
1. former parent before former children
2. former parent after former children

This assumes the student will not use "former parent in the middle of former children", as that would be odd.

Then, the tests could be made to consider trees made with **either** of these orderings as correct.

However, this makes the test more complex. I'm not sure I like this solution, myself.

It may be that the desire to let the student choose the internal representation will trump the minor inconvenience of having to use a specific ordering.

Note that the specific ordering hurts slightly more in F# because we are forced to append a one-element list, O(n) in the existing list's length, whereas prepending would be much cheaper. In C# I don't think there is the same disparity in cost, so the answer in C# is more likely to be to leave it as-is.

(We are both mirroring comments between C#'s https://github.com/exercism/xcsharp/issues/191 and F#'s https://github.com/exercism/xfsharp/issues/295)

**Comment by balazsbotond** [comment]
I haven't yet solved this exercise, and I've just quickly skimmed the README. But I really liked that I could define my own data structures in previous ones. You can learn a lot more from implementing both the data structure and the algorithm.

As far as I can see, because the implementation is fully encapsulated, the student is free to override Equals to make node equality independent of child order. Maybe we could add a new test case to ensure that, but that isn't strictly necessary.

**Comment by robkeim** [comment]
I also haven't implemented this exercise yet, but here's my $0.02...

I think that either approach is valid but it's worth making it explicit whichever direction we decide to go. For this exercise, the focus isn't about keep the order of the children, so I would say moving to have an order independent comparison seems logical.

@petertseng said:
> I think it would be beneficial if the tests did not care about the ordering of the children, since trees probably don't care about the ordering of their children

While I agree that's probably the case for this exercise, the ordering of the children is critical for all sorted trees, so that doesn't hold in the general case.

**Comment by ErikSchierboom** [comment]
For now, I'm slightly in favor of just leaving the exercise as it is. Yes it is an inconvenience that the order matters, but the student is given more freedom on the data structure implementation.

**Comment by balazsbotond** [comment]
@ErikSchierboom if I understand the tests correctly, they don't necessarily enforce a specific order - if you override `Equals`, you can make them pass even if the children are ordered differently in your data structure.

And if you use a `Set` in F# to represent the set of children, you get this `Equals` implementation for free. In C#, you need to implement `Equals` to use `HashSet.SetEquals` for comaparing the children.

So I also vote for not modifying the tests.

**Comment by ErikSchierboom** [comment]
@petertseng I think I'll close this issue and leave the exercise as is. Would that be okay with you?

**Comment by petertseng** [comment]
Given the factors discussed:

* It's important to give the student freedom in implementation
* The student can override Equals to make the order not matter
* The proposed change would increase test complexity

It seems the best way is to leave the exercise as is.

The issue stated to "consider", and it's been considered, so from my point of view, the mission is accomplished! =D
