### ISSUE TITLE
Replace NUnit with Xunit

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#193]
Xunit has slowly but steadily been replacing NUnit as the favored testing framework. Virtually all open-source Microsoft code now uses Xunit as the unit-testing framework. The integration with .NET Core is thus also better, as Microsoft has invested in Xunit for its own software and thus has to keep it running. An example of this improved integration is the fact that there is an Xunit template available in the .NET CLI.

p.s. I'm already working on this :)

**Comment by ErikSchierboom** [comment]
You can check my progress [here](https://github.com/ErikSchierboom/xcsharp/tree/xunit). I've done the initial conversion, now I've got to check if all tests still run correctly and if something has been broken.

**Comment by robkeim** [comment]
Progress is looking great so far @ErikSchierboom! I'd do a more thorough review once you send the final PR.

**Comment by ErikSchierboom** [comment]
With #199 merged, this issue can now be closed! 🎉
