### ISSUE TITLE
Create project for each exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#198]
To help users get started programming, we should provide the user with a skeleton .csproj file. This .csproj file should work with the .NET CLI and run on .NET Core.

**Comment by GalaDe** [comment]
Hi @ErikSchierboom, I would love to help you with these tickets. Could you please give me a more details what exactly should be done for this particular ticket. I think this ticket would be the easiest to start. What do you think?

Thank you in advance,
Galina.

**Comment by ErikSchierboom** [comment]
@GalaDe Well, this ticket is already included as part of [this PR](https://github.com/exercism/xcsharp/pull/199), but I could certainly use your help! Here are some of the things you could do:

- The simplest option is to work on the issue on using static classes for the implementation files (#207)
- I would love it if you would try and see if you can build the projects in my [PR](https://github.com/exercism/xcsharp/pull/199). Do do that by checking out the PR locally, and then run `build.cmd` on Windows or `build.sh` on Mac OS/Unix. Note: the latter requires Mono to be installed due to FAKE (the build script) only running on the full .NET Framework. You could also check if you can can build and test the exercises individually, by running `dotnet restore` followed by `dotnet test` from within an exercise's directory
- You can also examine the contents of the project and stub implementation files, to see if you find anything odd.
- You could also work on replace our test case tests to individual tests (#194)
- You could start on updating the documentation based on the PR (see #146)
- A very short and simple PR is to add a reference to the Gitter room to the docs (see #208)
- The `xunit` and `xunit.runner.visualstudio` packages are no longer RC's. You could update the references to these packages. 

Personally, I would be thrilled if you would just look at my PR and try to get things working on your machine. If you'd want to do that, please keep track of any weird things you might find. If you could test things using not only the command-line .NET CLI, but also using several other editors (VS 2017, VS Code, Project Rider or Visual Studio for Mac), that would also be very useful.

Note that you'll need the latest versions of all these IDE's to be able to work with the updated projects. In all but the VS Code case, that means using beta/RC releases.

To be able to build and test the updated project files, you'll need to have the .NET CLI RC4 installed. For instructions on how to do that, see: https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md

Note that for all these exercise, you'll have to base your commits on my [PR](https://github.com/exercism/xcsharp/pull/199). 

Please let me know if you need more information or if you have chosen one or more item(s) to work one. That way we won't be interfering with each other :) It might help to assign yourself to the relevant issue, I've also done that for the issues I'm working on.

 Thanks for the offer by the way, it's much appreciated!

**Comment by GalaDe** [comment]
Hi @ErikSchierboom, Thank you so much for your response.  Sorry for asking you stupid questions, but I'm new to open source projects:) and GitHub... How can I download your PR? Is the VS 2015 version would be ok? I will start looking at your PR and get things working on my machine first.  This will help me to at least understand how everything works. 

Thank you in advance!

**Comment by ErikSchierboom** [comment]
You're welcome, thanks a lot for being willing to help. I'll come back to you later today with instructions, alright?

**Comment by GalaDe** [comment]
Great! Thank you so much @ErikSchierboom!

**Comment by ErikSchierboom** [comment]
@GalaDe As you are new to open-source, I'll assume you are also new to how to do PR's :) If not, just ignore this :)

The first step to creating a PR will be to fork this repository, which means you'll have your own copy of everything in this repository. To do that, you can probably best follow [these instructions]. Once you have finished following the steps in that document, you'll have cloned your own copy to your local machine. You can read all both forks on [this page]. Once you are a little bit acquainted with forks, it's on to the coding!

As a first PR, I think it would be best if you try to do a very simple PR, with limited scope. Just to get the hang of things. The most obvious candidate would be #208, which involves adding a link to the `docs/RESOURCES.md` file. To fix this, should first create a new branch in your locally cloned repository (which is your fork). Then, make the changes and commit them. Next, you push your local branch to your remote (fork) repository, which you do using `git push origin <branch-name>`. The final step is then to create a PR from your branch, which you can find instructions for [here](https://help.github.com/articles/creating-a-pull-request/#changing-the-branch-range-and-destination-repository). We (the maintainers) will get notified and look at your PR, and when all is well, merge it.

If you are not new to PR's, forks and such, you may want to dive right in. To make things easier for your to work with, I've also pushed my PR as a separate [branch](https://github.com/exercism/xcsharp/branches). That means that you only have to clone this repository and not actually deal with my PR :) 

Having forked this repository, you should thus have access to the `dotnet-core` branch, which you should checkout. You now have access to my PR's contents, which you can then examine. The safest option is to use just the .NET CLI tool (RC4, see link in a previous comment) to test everything. VS 2015 will not work unfortunately, as they don't (and will not) support the new .csproj format. To use Visual Studio, you'll have to use the VS 2017 RC. You can also try VS Code as an editor, which has a nice C# extension that works okay-ish.

It's probably best that we continue our conversation in the newly-added Gitter room: https://gitter.im/exercism/xcsharp So if you have any further questions or remarks, please post them there! Good luck and enjoy yourself! Don't hesitate to ask questions.

**Comment by GalaDe** [comment]
Hi @ErikSchierboom, Yes, I'm new to public repositories:) Thank you for the explanation! By the way, I will be off-line until next Monday, will start work on this on Tuesday:)

**Comment by ErikSchierboom** [comment]
@GalaDe No problem!

**Comment by ErikSchierboom** [comment]
With #199 merged, this issue can now be closed! 🎉
