### ISSUE TITLE
Implement C# exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcsharp#2]
Copied from exercism/exercism.io#1125

-----

To implement C# in a lightweight manner, we need to sidestep creating a project file for every exercise. Using a project also makes it difficult to port to various platforms.

### Linux

TBD

### Mac

* Install [MonoDevelop](http://www.mono-project.com/Mono:OSX#Installing_Mono_on_MacOS_X)

* Download [NUnit](http://nunit.org/?p=download)

* Build, Link and Run the created DLL

```
dmcs Bob.cs BobTest.cs /r:/Users/burtlo/Downloads/NUnit-2.6.3/bin/nunit.framework.dll -target:library
monolinker -a /Users/burtlo/Downloads/NUnit-2.6.3/bin/nunit.framework.dll -a Bob.dll
mono /Users/burtlo/Downloads/NUnit-2.6.3/bin/nunit-console.exe output/Bob.dll
```

* Clean up

```
rm -rf output
```

### Windows

TBD

## Minimum Exercises to Implement

The following exercises are required to be created for the path to be launch.

- [x] bob
- [x] hamming
- [x] word-count
- [x] anagram
- [x] nucleotide-count
- [x] phone-number
- [x] grade-school
- [x] robot-name
- [x] leap
- [x] etl

## Additional Exercises to Implement

After the initial set of exercises the following should be implemented to have a more complete test suite.

- [x] meetup
- [x] twelve-days
- [x] space-age
- [x] gigasecond
- [x] triangle
- [x] scrabble-score
- [x] roman-numerals
- [x] binary
- [x] prime-factors
- [x] raindrops
- [x] allergies
- [x] strain
- [x] atbash-cipher
- [x] accumulate
- [x] crypto-square
- [x] trinary
- [x] rna-transcription
- [x] sieve
- [x] simple-cipher
- [x] octal
- [x] luhn
- [x] pig-latin
- [x] pythagorean-triplet
- [x] series
- [x] difference-of-squares
- [x] secret-handshake
- [x] wordy
- [x] hexadecimal
- [x] largest-series-product
- [x] kindergarten-garden
- [x] binary-search-tree
- [x] matrix
- [x] robot-simulator
- [x] nth-prime
- [x] palindrome-products
- [x] pascals-triangle
- [x] beer-song
- [x] sum-of-multiples
- [x] queen-attack
- [x] saddle-points
- [x] ocr-numbers
- [x] simple-linked-list
- [x] linked-list

**Comment by ErikSchierboom** [comment]
I am working to implement more of the missing exercises (beer-song and kindergarten-garden at the moment). However, I was wondering if we should use C# 6 features in the examples or not?

**Comment by jwood803** [comment]
If I recall, it comes with VS 2015 Community edition, so that may be ok.

**Comment by ErikSchierboom** [comment]
Okay, I'll use C# 6 then. It's only the examples though, the tests themselves should be C# 5 I think.

**Comment by ErikSchierboom** [comment]
@kytrinyx PR #53 added four new exercises: 

1. beer-song
2. pascals-triangle
3. saddle-points
4. kindergarten-garden

Could you update your initial comment to check these exercises?

**Comment by kytrinyx** [comment]
Done. Thanks!

**Comment by ErikSchierboom** [comment]
@kytrinyx The `linked-list` exercise is listed as not completed, but it has in fact already been added

**Comment by kytrinyx** [comment]
Ah, thanks.

**Comment by kytrinyx** [comment]
It's in the list twice, actually.

**Comment by kytrinyx** [comment]
OK, deleted the superfluous one.

**Comment by ErikSchierboom** [comment]
@kytrinyx The list of open issues contains the `point-mutations` exercise, which is now deprecated as per https://github.com/exercism/x-common/issues/184.

**Comment by bressain** [comment]
@ErikSchierboom removed

**Comment by ErikSchierboom** [comment]
@bressain Thanks! Only three to go :)

**Comment by ErikSchierboom** [comment]
The `matrix` exercise has been added: #57

**Comment by ErikSchierboom** [comment]
With #58 and #59 merged, all exercises have now been added! :tada:

**Comment by jwood803** [comment]
Awesome job, @ErikSchierboom! :beers:

**Comment by bressain** [comment]
Thought I'd never see the day :raised_hands:

**Comment by kytrinyx** [comment]
Holy smokes, this is great! Thanks y'all :)
