### ISSUE TITLE
Add link to xcsharp gitter room in docs

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#208]
I've just created a Gitter room for this repository at: https://gitter.im/exercism/xcsharp We should add this link to the documentation.

**Comment by ErikSchierboom** [comment]
The link should be added to the Social Media section of the `docs/RESOURCES.md` file.

**Comment by jmbradnan** [comment]
I am looking for a first patch - mind if I pick this one up?

**Comment by ErikSchierboom** [comment]
Not at all. Be my guest!

**Comment by jmbradnan** [comment]
great, since I haven't done this before I may have questions, best to use
the gitter room for those?    Is this
http://exercism.io/languages/csharp/contribute the best place to get
started if you are a first time contributor?

**Comment by ErikSchierboom** [comment]
Yes, the gitter room is best suited for questions. The contributions page on exercism.io gives you an idea on what you could be working on. For more concrete tasks, please check the issues section of this repository. Enjoy!
