### ISSUE TITLE
Add hints to some exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#209]
@abo64 added [this issue](https://github.com/exercism/xscala/issues/220) to the Scala track, which I thought was a brilliant plan. I'm just gonna literally copy-and-paste that issue's text:

>Most exercises have their own favorable solutions and characteristic pitfalls.
To give people some guidance and avoid writing repetitive or similar code comments again and again
we should add a HINTS.md file to any exercise where it makes sense.

>Especially the first couple of exercises should have such a file to assist beginners.
Another case is exercises dealing with special features of the language like `option` or `async`.

We should make a list of exercises for which some hints can be added. Of course, the first exercises should be more hint-heavy than the latter, although even for advanced exercises hints can be very useful. One example of this are the text parsing exercises, where we could guide people to using Sprache.

**Comment by ErikSchierboom** [comment]
RESERVED: will contain the list of exercises to add hints to

**Comment by GalaDe** [comment]
Hi @ErikSchierboom, I would like to work on this ticket. As I understood correctly, we just need to create for each of the above exercises HINTS. md files, right?

**Comment by ErikSchierboom** [comment]
Correct! You can check some of the existing Hints.md files to see how they are structured. It is probably best to send one PR per Hints.md file. If you have any questions, just ask.

**Comment by GalaDe** [comment]
@ErikSchierboom Sounds Good!

**Comment by robkeim** [comment]
Thanks for pulling this together @ErikSchierboom!

**Comment by GalaDe** [comment]
Hi @ErikSchierboom, is it something what you are looking for:

https://github.com/GalaDe/gklikh-hmwk2/blob/master/Hints.md

**Comment by ErikSchierboom** [comment]
@GalaDe Yeah, that's what I mean! I have two small nits. 

1. Perhaps rephrase "This exercise requires you to perform operation with collection of data." a little bit, e.g. to "This exercise requires you to process a collection of data."
1. A space is missing between "LINQ" and "(Language Integrated Query)"

Other than that, this is great! You could add this hint to both the `difference-of-squares` and `sum-of-multiples` docs and send it as a PR. By the way, the `accumulate` exercise also had the LINQ hint listed, but that should actually be a link to a page about extension methods.

**Comment by GalaDe** [comment]
@ErikSchierboom, you want me to use this link instead the link which was used in my example:

https://msdn.microsoft.com/en-us//library/bb383977.aspx

**Comment by ErikSchierboom** [comment]
@GalaDe Just for `accumulate` please.

**Comment by GalaDe** [comment]
@ErikSchierboom Ok, most of them will be done today. I will upload them to the right repository this time:)

**Comment by jmbradnan** [comment]
@GalaDe I was also thinking of picking some of these up - which ones are candidates for me to work on (if any?)  Not sure if you have done all of them or just a subset.

**Comment by GalaDe** [comment]
@ErikSchierboom, all of them are completed:  

 accumulate (extension method docs)
 allergies (bitwise operations)
 alphametics (hint to non brute-force algorithm (see example); link to Sprache text parsing library
 bank-account (link to how to deal with concurrency)
 beer-song (hint to not encoding the structure (see example)
 clock (link to IEquatable docs)
 custom-set (link to IEquatable docs)
 difference-of-squares (link to LINQ docs)
 diffie-hellman (link to BigInteger docs)
 food-chain (hint to not encoding the structure (see example)
 forth (link to Sprache text parsing library)
 hangman (link to events docs)
 sgf-parsing (link to Sprache text parsing library)
simple-linked-list (link to IEnumerable docs)
sublist (link to IComparable docs)
 sum-of-multiples (LINQ docs)
 twelve-days (hint to non encoding the structure (see example)
 variable-length-quantity (link to bitwise operators)
 wordy (link to Sprache text parsing library)

**Comment by GalaDe** [comment]
@ErikSchierboom pull request created. By the way, why I can't mark checkboxes with the complete exercises in your post?

**Comment by ErikSchierboom** [comment]
@GalaDe You can't check the checkboxes as you are not a maintainer of this repository, hence you don't have the rights.

**Comment by GalaDe** [comment]
Here is the list which has to be done:

list-ops (link to Func docs)
 nth-prime (link to lazy sequences (see example)
 nucleotide-count (link to IDictionary<TKey, TValue> documentation)
 palindrome-products (link to tuple documentation)
 proverb (hint to non encoding the structure (see example)
 saddle-points (link to tuple documentation)
word-search (link to tuple documentation)
 zebra-puzzle (link to how to use lazy sequences, to improve performance)
 zipper (link to how to deal with custom equality)


Unfortunately, I will not be able to complete them until March 28th.  @jmbradnan, do you wanna work on them?

**Comment by ErikSchierboom** [comment]
@GalaDe I've updated the list and added "(in progress)" for the HINTS you have submitted in your PR. Once that PR is merged, I'll check them in the list. Thanks for the great work!

**Comment by jmbradnan** [comment]
yes I will take a look at these.

**Comment by jmbradnan** [comment]
I am using other examples to hopefully get the formatting right, if there is a guideline for how to mark up the text for proper rendering let me know.

**Comment by jmbradnan** [comment]
It looks like the hint for the proverb exercise is for the beer-song exercise.   I checked the HINTS file in the xfsharp/exercizes and it also contains the beer-song hint, is this an error?    Doesn't seem like it is the right hint for that exercise

**Comment by ErikSchierboom** [comment]
@jmbradnan No that is not an error, the hints are actually the same, as the exercises are very similar.

**Comment by GalaDe** [comment]
Hi @ErikSchierboom! I'm back:) Do you still need help with this ticket?

**Comment by ErikSchierboom** [comment]
I'd love some help 😀

**Comment by jmbradnan** [comment]
Hey folks, getting back online after spring break, I think the ones that still remain are:

list-ops (link to Func docs)
nucleotide-count (link to IDictionary<TKey, TValue> documentation)
palindrome-products (link to tuple documentation)
saddle-points (link to tuple documentation)
zebra-puzzle (link to how to use lazy sequences, to improve performance)
zipper (link to how to deal with custom equality)

Does that look right?   Happy to help as well.

**Comment by ErikSchierboom** [comment]
@jmbradnan sounds good. Perhaps you and @GalaDe can divide them amongst yourselves?

**Comment by jmbradnan** [comment]
sounds good to me @ErikSchierboom     @GalaDe I am going to look at list-ops problem next.

**Comment by jmbradnan** [comment]
scratch that, it looks like list-ops already has a HINTS.md file.   All of the others I list above do need HINTS, so I will look at next one in list ->nucleotide-count

**Comment by jmbradnan** [comment]
btw, @ErikSchierboom there is a small typo in the HINTS for list-ops, I am going to just fix this and submit

**Comment by GalaDe** [comment]
Hi @jmbradnan, I will work on these three today: 

 word-search (link to tuple documentation)
 zebra-puzzle (link to how to use lazy sequences, to improve performance)
 zipper (link to how to deal with custom equality)

**Comment by GalaDe** [comment]
Hi @ErikSchierboom, could you please mark nucleotide-count exercise and word-search as completed.

**Comment by ErikSchierboom** [comment]
@GalaDe Sure, forgot about that. I've just updated the list.

**Comment by GalaDe** [comment]
@ErikSchierboom, Thank you!

**Comment by jmbradnan** [comment]
ok @GalaDe, I think that means these remain:
palindrome-products (link to tuple documentation)
saddle-points (link to tuple documentation) 
will take a look later today.

**Comment by GalaDe** [comment]
@jmbradnan If you haven't started working on the house and saddle-points hints I can take them.

**Comment by jmbradnan** [comment]
@GalaDe yes please do - school just starting for me so busy for next few days.

**Comment by GalaDe** [comment]
@jmbradnan Sounds good! Good luck with school!

**Comment by GalaDe** [comment]
@ErikSchierboom, I guess we can close this ticket:)

**Comment by ErikSchierboom** [comment]
With huge thanks to @jmbradnan and @GalaDe, this issue can now be closed! Thanks a lot!

**Comment by GalaDe** [comment]
Ehyyyyy!!!!!
