### ISSUE TITLE
Speed up build and testing by using solutions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#216]
See: https://github.com/dotnet/cli/issues/5099 

Note: this is related to PR #199.

**Comment by ErikSchierboom** [comment]
The solution file has been added, and we can get some huge speed-ups by restoring and building a solution instead of the individual projects. A small, not-so-scientific test reduced the restore time by two minutes! I expect similar gains when building the projects. Unfortunately, there is no solution-level test support yet, but it has been [logged as an issue](https://github.com/Microsoft/vstest/issues/411).

**Comment by ErikSchierboom** [comment]
To simplify our build script, we could create separate solution files for the different build purposes. So one `Exercises.tests.sln`, one `Exercises.refactoring.sln` and `Exercises.build.sln`.

**Comment by tushartyagi** [comment]
PR #225 is using solution based builds.

**Comment by ErikSchierboom** [comment]
This has been fixed in #226.
