### ISSUE TITLE
GradeSchoolTest not according to README

### ISSUE THREAD

**Issue by MahrWe** [exercism/xcsharp#289]
The Test: "Student_names_with_grades_are_displayed_in_the_same_sorted_roster" is not according to Readme-file. 
See README.md lines 13ff: - Get a sorted list of all students in all grades.  Grades should sort as 1, 2, 3, etc., and students within a grade should be sorted alphabetically by name.
"students WITHIN a grade should be sorted alphabetically"

Proposed new Test:
```
    [Fact]
    public void Student_names_with_grades_are_displayed_in_the_same_sorted_roster()
    {
        var school = new School();
        school.Add("Peter", 2);
        school.Add("Anna", 1);
        school.Add("Barb", 1);
        school.Add("Zoe", 2);
        school.Add("Alex", 2);
        school.Add("Jim", 3);
        school.Add("Charlie", 1);
              
        var actual = school.Roster();
        
        var expected = new[] { "Anna", "Barb", "Charlie", "Alex", "Peter", "Zoe", "Jim" };
        Assert.Equal(expected, actual);
    }```

**Comment by ErikSchierboom** [comment]
@MahrWe Ah, good catch! Perhaps what we actually should be returning is a dictionary, if I look at other tracks. Would you be interested in doing a PR for this?

**Comment by robkeim** [comment]
I was going just about to respond @ErikSchierboom but you're too fast :) @MahrWe feel free to submit a PR and we can approve it.

**Comment by MahrWe** [comment]
Actually I am not sure how to do that, Pull the Repo, make changes and then.. Push to a new Branch, maybe?

**Comment by MahrWe** [comment]
@ErikSchierboom, @robkeim sorry I am new to github

**Comment by ErikSchierboom** [comment]
There are some good tutorials out there:

- https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
- https://yangsu.github.io/pull-request-tutorial/
