### ISSUE TITLE
exercise testing problem.

### ISSUE THREAD

**Issue by IngussA** [exercism/xcsharp#294]
So i've been working on the bob exercise in C# and everything was going fine untill I took a break and had a go at it again later, I ended up getting an error in the picture below. Now I am still getting the error on a fresh version of the exercise so it isn't affected by any actual code in the Bob.cs or BobTest.cs files and I did replace all of the other ones with a fresh batch, still no dice.
![error](https://user-images.githubusercontent.com/10990068/26882507-842b087c-4b92-11e7-97c3-f96c8c7a6944.PNG)

**Comment by ErikSchierboom** [comment]
@IngussA Could you check which files are in the folder where the project and Bob.cs are? And how are you compiling? Using the CLI, Visual Studio, VS Code or Rider?

**Comment by IngussA** [comment]
@ErikSchierboom Thank you for your help, after you mentioned what files are in the folder I decided to move the version folder outside of the bob folder and it seemed to have fixed the issue.

**Comment by ErikSchierboom** [comment]
@IngussA Good to hear! Enjoy the track.
