### ISSUE TITLE
Include canonical data version number in generated test files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#297]
The tests generator should include the canonical data version number in the generated test files.

**Comment by robkeim** [comment]
Good idea @ErikSchierboom, and I think a next step could be to have the test generator pull the canonical data from the server check if there are any differences and update the differences all in a single command line. That would reduce the maintenance burden of keeping up with the canonical data which seems to have a fairly high level of churn.

**Comment by robkeim** [comment]
I'm catching up on things now and realized that you're already many steps ahead of me on the auto-generating all cases :)
