### ISSUE TITLE
C#: NUnit test suite not working with built in mono on OSX please read suggestion

### ISSUE THREAD

**Issue by naruse** [exercism/xcsharp#34]
The tests assertions are written in the constraint-based model (which is pretty neat!) BUT even the latest mono (3.12.1) comes with NUnit 2.4.8, and the tests just dont work in the constraint-based model for that version; I solved this by downloading the latest version of NUnit (2.6)
found here http://nunit.org/index.php?p=download 

How to repro: just try to build the 1rst excercise on C#

naruse@MacBook-Pro ~/exercism/csharp/leap $:dmcs Leap.cs LeapTest.cs -reference:nunit.framework.dll
LeapTest.cs(9,40): error CS0103: The name `Is' does not exist in the current context
LeapTest.cs(16,40): error CS0103: The name`Is' does not exist in the current context
LeapTest.cs(23,40): error CS0103: The name `Is' does not exist in the current context
LeapTest.cs(30,40): error CS0103: The name`Is' does not exist in the current context

as you can see it throws an error regarding the Is class (which is part of NUnit).

My suggestion is to say at least that it in order for the tests to run, it needs to run on a NUnit version > 2.4 and this NUnit version doesnt come embebed in the latest mono (3.12.1). so its better to download a version of NUnit from the web page ;)

**Comment by kytrinyx** [comment]
Yeah, that sounds like a good approach.

This is the page in the docs https://github.com/exercism/docs/blob/master/app/pages/languages/getting-started-with-csharp.md (in case someone gets to it before I do).

**Comment by ErikSchierboom** [comment]
@naruse The updated examples all use NUnit v3. The documentation has also been updated (e.g. [docs/INSTALLATION.md](INSTALLATION.md). Perhaps you'd be willing to check the docs to see if they indeed properly guide you to using NUnit?

**Comment by ErikSchierboom** [comment]
@naruse Unless you disagree, I think we'll close this issue.
