### ISSUE TITLE
provide some utitlity to build exercises from CLI

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcsharp#37]
For developers using linux it is quite uncommon to install a large IDE like xamarin/monodevelop. Especially this is true for small projects like exercism exercises.

Is it possible to provide a Makefile or something equivalent that makes compiling/running tests from bash possible?

**Comment by kytrinyx** [comment]
I have the same command-line bias (but I've never worked with C#). Do you know if there are any resources that talk about how that has been done elsewhere?

**Comment by NobbZ** [comment]
AFAIK Microsoft uses some buildfile-format called msbuild. Some googling showed up the following ressource: https://msdn.microsoft.com/en-us/library/dd576348.aspx

These files can be run from commandline using `msbuild.exe` on windows or `xbuild` (from mono) on linux and Mac OSX. At least, thats the theory.

**Comment by jwood803** [comment]
I dislike MSBUILD and find it very hard to work with. :}

However, I have been playing around with FAKE which should be the solution that's needed here.

**Comment by NobbZ** [comment]
MSBUILD seems to have the advantage, that the msbuild-files can be opened by Visual/Xamarin Studio and monodevelop as projects for everyone who really wants that, can FAKE do this too?

**Comment by jwood803** [comment]
FAKE scripts are just F# script files that can be opened in either editor. Feel free to read some on it [here](http://fsharp.github.io/FAKE/) that has some examples to see if that will work for you.

**Comment by NobbZ** [comment]
So using FAKE would pull in F# as another dependency for trying out C#? XBuild is part of mono while F# has to be installed additionally.

**Comment by NobbZ** [comment]
Has there been any progression on this or a decission at least?

**Comment by bressain** [comment]
I haven't had a chance to look at it unfortunately, but it's an interesting problem.

While Xamarin studio may feel heavy, it's probably the easiest way to get Mono installed. And because of how .Net currently requires proj files, it might be easier to have an IDE manage that.

If someone wants to take a shot at this before I can look into it, we take pull requests :-D

**Comment by ErikSchierboom** [comment]
I have been looking at various build systems lately, and MSBuild is not the best option to do cross-platform building. FAKE is a nice alternative, but it requires you to write the configuration file in F#. However, there is also another library named [CAKE](http://cakebuild.net/) that allows the configuration to be specified in a C# DSL. 

Using FAKE or CAKE would allow the tests to be run from the command-line, either on Windows, Mac OS X or Linux. However, FAKE or CAKE can only build solution (.sln) or (.csproj) files, not individual C# files. At the moment, we don't supply any of those, so users would have to create them first. Is there a reason why we don't supply a solution file? If this is not desirable, I probably could create some code that uses Roslyn to dynamically create a solution/project. Should we go this route, I could also create solutions/projects for the files in a single folder, which would allow us to run tests for a single, specific exercise.

I'm very interested in your thoughts on this subject.

**Comment by ErikSchierboom** [comment]
I managed to get something working for F#: https://github.com/exercism/xfsharp/pull/55
I'll be looking into getting this to working for C# too.

**Comment by ErikSchierboom** [comment]
I have a FAKE build script that currently builds all our examples. It would be easy to extend this to a general script with which you can run all or one exercise.

The problem is that at the moment, it is not possible to a language track to have additional scripts automatically be fetched. For context, see this comment by @kytrinyx: https://github.com/exercism/xfsharp/issues/32#issuecomment-178821775

When support for this is added, I'll make sure we get a command-line build/test script for the C# track (and the F# track too).

**Comment by canweriotnow** [comment]
I think #146 will help with this... using .NET Core and VS Code makes it easy to not only build and run C# projects from the `dotnet` CLI, but VS Code adds extensive build support for Make, Rake, Fake, and Cake.

**Comment by ErikSchierboom** [comment]
It definitely will! See also #138

**Comment by petertseng** [comment]
I will not mind sharing the exact script I used to test on Linux

```bash
#!/bin/sh

set -e

if [ $# -eq 0 ]; then
  srcfile=$(ls -1 *.cs | grep -v Test)
  if [ -z "$srcfile" ]; then
    echo "found no .cs files, run in a directory with one, or specify one."
    echo "usage: $0 [srcfile [testfile]]"
    exit 1
  fi
fi

if [ $# -lt 2 ]; then
  testfile=*Test.cs
  testdll="$(echo $testfile | cut -d. -f1).dll"
else
  testfile=$2
  testdll="$(echo "$testfile" | cut -d. -f1).dll"
fi

srcdll="$(echo "$srcfile" | cut -d. -f1).dll"
nunit=/usr/lib/cli/nunit.framework-2.6.3/nunit.framework.dll

mcs -t:library $srcfile
mcs -t:library -r:$nunit,$srcdll $testfile
nunit-console --noxml $testdll
rm $srcdll $testdll
```

will be good to see `dotnet test` improve on this.

**Comment by ErikSchierboom** [comment]
This issue will be taken care of when #200 completes.
