### ISSUE TITLE
Enhance description on how to set up Xamarin/monodevelop on Mac OSX/Linux

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcsharp#38]
I wanted to try some C# exercises in Xamarin until we have a solution for #37, but I am not able to open the actual exercise as a project in it. Xamarin wants to create some additional subfolders with subprojects in it.

I haven't find a way to import exercism files as exisitng sources.

Also there are 2 images on the description regarding set up/testrunning on Mac, but they don't show up/ don't load.

**Comment by jwood803** [comment]
That's probably my fault. I'll double check the docs for the images.

I've been using Xamarin for a little while on the Mac but I'm totally unfamiliar with Monodevelop on Linux...

**Comment by NobbZ** [comment]
As far as I understand the Xamarin Studio/monodevelop thingy, it is just that Xamarin Studio is the commercial Mac OS version of monodevelop.

At least monodevelops aboutpage tells me, that it is copyrighted by Xamarin Inc. since 2011 (and contributors), also it looks very similar to the screens that are shown on http://www.xamarin.com/studio (excluding some controls that seem to be themed by my window manager).

**Comment by jwood803** [comment]
I believe that's correct. I can try to ping some folks who use it with Linux to see if they have any additional tips.

**Comment by AlexMcConnell** [comment]
Did you ever figure this out, NobbZ? It hasn't been fixd.

**Comment by NobbZ** [comment]
Sorry, I never tried it further but used MSVC from a windows VirtualBox I still had floating around. But gave up on .NET in general very fast.

**Comment by AlexMcConnell** [comment]
Dang. I don't have much interest in .NET backend, but I'm very interested in Xamarin and Unity.

**Comment by ErikSchierboom** [comment]
Well, once the new .NET Core CLI is released (only preview releases now), we will be able to significantly make things easier to start. Hopefully you will want to try things again then.

**Comment by AlexMcConnell** [comment]
I've actually managed to get it working via command line, though I have to change all the tests to Assert.AreEqual statements rather than Assert.That(Is.Equal) statements. Probably just need to import another library for that, but IDK.

**Comment by ErikSchierboom** [comment]
@NobbZ With #199 merged, I think this issue can now be closed. To be clear, we've updated the track to be based on the .NET CLI, which is cross-platform and thus has the same interface on all platforms. You should thus now have things nicely working on .NET Core!
