### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcsharp#45]
After I encountered #44, I simply removed all the `Ignore` things and tried to run. But then I do get an errormessage that I need to have an executable project. So how can I set up MS VS to actually run the tests instead of trying to run the projects executable?

**Comment by NobbZ** [comment]
OK, after downgrading to NUnit 2.6.4 I was able to find that GUI-Runner mentioned in the help.

Is there a way tu run tests from inside Visual Studio?

**Comment by jwood803** [comment]
@NobbZ What version of VS are you using? I *think* they may have included it to automatically pick up NUnit tests, but I'll have to double check it.

**Comment by bressain** [comment]
You might need to install an adapter for VS2013 http://www.nunit.org/index.php?p=vsTestAdapter&r=2.6.2

**Comment by NobbZ** [comment]
OK, installing that adapter works. Perhaps mention this in the docs?

I do realise that running the tests from inside VS is somewhat slower than using the NUnit GUI, but switching away from VS over to that GUI eats up all of the benefits I had by using it. Also using VS as the test runner gives me the very strong benefit of compiling before test, while I always forgot it when using that external GUI (which doesn't seem to be available in NUnit 3.0 anyway).

**Comment by robkeim** [comment]
@NobbZ I updated the test readme with this information, so I'm going to go ahead and close this. Let me know if you feel something is missing/incomplete.
