### ISSUE TITLE
Launch C# track!

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcsharp#7]
@dinkelburt I've added you as a committer on the C# team. Thanks so much for porting all those exercises!

In order to launch the track officially we're going to need:

- [x] a getting started with C# page
- [x] a way to recognize submissions as C#
- [x] an ordered list of exercises
- [x] a submodule in x-api
- [x] list csharp in the active languages on exercism.io

I've got the last four covered, but the help page is going to be tricky. @dinkelburt would you be willing to give that one a shot? There's some detail in #2 but I don't have the background necessary to evaluate whether or not it's going to make sense :)

We'll also need people to nitpick the C# track. That shouldn't be too difficult, since it's a popular language (I'm more worried about Rust and other niche languages).

See the [exercism.io CONTRIBUTING.md file](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#creating-a-new-language-track) for details.

**Comment by jwood803** [comment]
I'm guessing this can be closed. :]

**Comment by kytrinyx** [comment]
Hah. Yeah, it does seem that way. Thanks!
